version: "3.9"

services:
  shortify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortify
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/url_shortener
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    hostname: shortify
    networks:
      shortify_network:

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      shortify_network:
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - shortify
    networks:
      shortify_network:
  
networks:
  shortify_network:
    driver: bridge

volumes:
  db_data:
