global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'shortify_default_metrics'
    static_configs:
      - targets: ['shortify:8000']

  - job_name: 'shortify_custom_metrics'
    metrics_path: '/custom_metrics'
    static_configs:
      - targets: ['shortify:8000'] 